### ISSUE TITLE
Seed rhythm data on deploy/rebase

### ISSUE THREAD

**Issue by gregdyke** [ManSangSin/Rhythm-Code#3]
## Technical task

This ensures that the project is always deployed fresh, with up to date DDL and only seeded data.

Additionally, when a commit changes the DDL, locally this gets reset

## Acceptance Criteria

1. Given _
   - When the project is deployed
   - Then a database is created/reset
   - And it is seeded with the data (DDL and DML) above
2. Given a seeding file exists
   - And I, as a developer, rebase onto main
   - When `npm [fill in here]` is executed
   - Then my database is created/reset
   - And it is seeded with the data from the seeding file

## Implementation Notes

1.
2.

## Checklist:

- [ ] I have defined the user story
- [ ] I have defined some acceptance criteria
- [ ] I have included any implementation notes
- [ ] I have included all relevant links

**Comment by mferryRV** [comment]
### Background
[DDL & DML](https://www.tutorialspoint.com/difference-between-ddl-and-dml-in-dbms)

Environments:
* “Production” - the real deal, deployed to real people - matched with main branch
* “Local” - simulating deployment on your computer - this is your branch
<img width="329" alt="image" src="https://github.com/ManSangSin/Rhythm-Code/assets/24232245/28bf4713-1e40-44cf-ad26-5a16cfad0af6">


Infrastructure as Code: databases are created and recreated automatically based on pre-written code (easy to recover from deletion)

### Tasks

- [x] Research [Postgres](https://www.postgresql.org/) database & seeding
- [x] Research how deployment works (Render, Cloud Foundry, **Docker**)
- [x] Research running a database locally (look at **Docker**)
- [x] Research how to share a locally run databases
- [x] Create a database locally
- [x] Make a seed file
- [x] Seed the database
- [x] Test restarting/re-seeding database
- [x] Make a script + README to help other developers start & seed local database
- [x] Automate database deployment with app deployment

3 hours, 3 hours, 3 hours, 1 hour, 1 hour, 3 hours, 20 minutes, 1 hour, 3 hours, unknown - 18+ hours

Not necessarily one week of work, aim to do the local development this week and deployment during next week's CYF Saturday

**Comment by mferryRV** [comment]
@ManSangSin - does our current solution reseed the production database on deployment?

**Comment by ManSangSin** [comment]
@mferryRV - it does not at the moment. I do have some code which I have tested last night on a separate repo (as I needed to push some random test commits and also test the building and deployment process on render) and it seems to be reseeding the production database properly after building and before deployment of the project on render. I'll submit a PR with the code today.
